services:
  - type: web
    name: EventManagementApp
    runtime: dotnet
    plan: free
    buildCommand: dotnet publish -c Release -o out
    startCommand: cd out && dotnet EventManagementApp.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
